### ISSUE TITLE
MqttClient works only as global scope variable

### ISSUE THREAD

**Issue by TechNyquist** [arduino-libraries/ArduinoMqttClient#7]
Hello everyone,

I noticed that MqttClient works only if it is declared as global: if I try to create a local instance in "setup()" that connects, publishes and disconnects, the flow hangs on the "print" method right after the "beginMessage". The same program works if MqttClient is declared in global scope instead of local.
Any particular reason for this?

Attached you have a zip with two ino files: one should reproduce the bug, and one should work, demonstrating the behaviour explained above.

[demo_ino_files.zip](https://github.com/arduino-libraries/ArduinoMqttClient/files/3407311/demo_ino_files.zip)

Best regards

**Comment by Rocketct** [comment]
hi @TechNyquist is this behaviour is due to memory allocation, declaring the object inside the setup, you never allow the correct allocation of memory for the HttpClient object memeber the consequence is that  when the beginMessage is end all the tructure instantiade inside are free and after when the print is called it execute the code until the memcopy in https://github.com/arduino-libraries/ArduinoMqttClient/blob/master/src/MqttClient.cpp#L655 and stop to work due to null point  .

To declare and use inside a function in this case the best solution could be declare the httpClient static in this case work fine.

**Comment by TechNyquist** [comment]
I see @Rocketct , thank you.
So should we expect some kind of future native "fix" for this from the mqtt library or we'd better stick to "manual" workaround (the one you suggested) right away?

**Comment by Rocketct** [comment]
you should use "manual" one, because this object born to be used like the gsm, gms client access and so on and so forth, you should declare it global and connect transmit and disconnet, as you need in the sketch.

**Comment by TechNyquist** [comment]
Ok, thank you @Rocketct .

**Comment by Rocketct** [comment]
find criticism on the constructor of the client now the index is assignedby defaul when instantiated and this fix your problem :)

**Comment by sandeepmistry** [comment]
This is fixed with the changes in #8. The fix will be included in the next release of the library.

**Comment by TechNyquist** [comment]
Ooh, @Rocketct  this is what we'd both call a "Colpo di scena" :)
Thank you guys.

**Comment by Rocketct** [comment]
ahah yes is exactly this :) welcome @TechNyquist

**Comment by sandeepmistry** [comment]
@TechNyquist thank you for your excellent issue report on this topic :)
