### ISSUE TITLE
Failure to connect to 127.0.0.1 (localhost) using Mosquitto Broker

### ISSUE THREAD

**Issue by Rhyzhang** [arduino-libraries/ArduinoMqttClient#87]
Hi,

I am following this guide for my school project: [https://docs.arduino.cc/tutorials/uno-wifi-rev2/uno-wifi-r2-mqtt-device-to-device]

The receiver code is basically the same as the one given in the example folder of this library.

When code works perfectly fine when using the broker "test.mosquitto.org" as shown below:
![image](https://user-images.githubusercontent.com/65325330/232160195-ba3238fc-4ca0-4ff6-aa7c-9e21d84048b8.png)

However, it fails when I try to connect to my local host.
![image](https://user-images.githubusercontent.com/65325330/232160382-a4270665-cb4b-4548-bd55-d39f92197e19.png)

I attempted to figure out if it was my localhost bugging out but it was working fine as I was able to publish.
![image](https://user-images.githubusercontent.com/65325330/232160592-a6db1b52-c320-436f-9f9f-04d3d1a2a9ba.png)
![image](https://user-images.githubusercontent.com/65325330/232160649-74c840f8-b3b6-46ac-ad71-107b22807d19.png)

I can't figure out why it can't connect to localhost.

Thank you,
Ryan

**Comment by imatrisciano** [comment]
By using `localhost` on arduino you are telling it that the MQTT broker is located on arduino itself. This is not the case, the broker is located on your computer. 

You should open a terminal on you computer and launch `ipconfig`. This will show you a bunch of information, but the only line you are interested in is `IPv4 Address`, this will look like `192.168.0.147` . This is the IP address of your computer. 

By connecting the arduino and the computer to the same network, you can access the broker on arduino by using that IP instead of localhost.
Note that that IP address is chosen by the DHCP server in your network and it can change. To prevent that you can disable DHCP on your computer, setting a custom IPv4, or you can configure your router to always assign the same IP to your computer
