### ISSUE TITLE
Linker error undefined reference to .. if I use the MQTT_CLIENT_STD_FUNCTION_CALLBACK

### ISSUE THREAD

**Issue by ma-bg** [arduino-libraries/ArduinoMqttClient#98]
I've added the example from here https://github.com/arduino-libraries/ArduinoMqttClient/pull/35#issue-597871517 to my code.

>```cpp
>MqttClient::MessageCallback callback = [this](MqttClient *client, int messageSize) {
>    Serial.print("Received message with topic: " + client->messageTopic());
>};
>mqttClient->onMessage(callback);
>```

Then I got the following error: 
```text
undefined reference to MqttClient::onMessage(std::function<void (MqttClient*, int)>)
```

If I use the plain C function pointer things work fine. Any idea what might trigger my problem?

I'm using Arduino IDE 2.2.1 with an Arduino Nano ESP32.

**Comment by per1234** [comment]
Hi @ma-bg. This feature is only available when the `MQTT_CLIENT_STD_FUNCTION_CALLBACK` macro is defined. 

Unfortunately the comment in the source code regarding this is misleading:

https://github.com/arduino-libraries/ArduinoMqttClient/blob/f2574327f8e29c792225514e2d5fa00791a4e581/src/MqttClient.h#L35-L36

The comment implies that you can simply add the `#define` directive to the sketch:

**MySketch.ino**:

```cpp
#define MQTT_CLIENT_STD_FUNCTION_CALLBACK
#include <ArduinoMqttClient.h>

// ...
```

But this is not possible. The reason is that this only defines the macro in the "[translation unit](https://wikipedia.org/wiki/Translation_unit_(programming))" of the sketch, but not in the translation unit of `MqttClient.cpp`, where the macro must also be defined. If the macro is not defined in that translation unit, you get an `undefined reference` error.

There are two approaches to using the feature:

- Define the macro globally via a [`-D` flag](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#index-D-1) in the compilation command.
- Define the macro in the library header file.

Arduino IDE 2.x does not provide an interface for the user to define arbitrary global macros so the former is only possible for Arduino IDE users by modifying the [compilation command pattern](https://arduino.github.io/arduino-cli/dev/platform-specification/#recipes-to-compile-source-code) in the boards platform. So the latter approach will be the best option for Arduino IDE users:

1. Open the `MqttClient.h` file of your local installation of the library in any text editor.
1. Change line 36 from this:
   https://github.com/arduino-libraries/ArduinoMqttClient/blob/f2574327f8e29c792225514e2d5fa00791a4e581/src/MqttClient.h#L36
   To this:
   ```cpp
   #define MQTT_CLIENT_STD_FUNCTION_CALLBACK
   ```
1. Save the file.

If you would like further assistance with the configuration of the library or the usage of this feature, you are welcome to post over on Arduino Forum:

https://forum.arduino.cc/

I'm sure we'll be able to help you out over there.

**Comment by ma-bg** [comment]
Hi @per1234 

I appreciate your detailed explanation & tecnical dive in. I changed my code and things work fine now.
